# Auto-generated file, do not edit!
SRCS = classes/object.c \
classes/node/childs.c \
classes/node.c \
types/vector3/comparisons.c \
types/vector3/operators.c \
types/vector3/other_operators.c \
types/vector3/operators_by.c \
types/vector3/other_operators_by.c \
types/vector3/len.c \
types/vector3/dot.c \
types/vector3/dist.c \
types/vector3/normalize.c \
types/vector3/clamp.c \
types/vector3/cross.c \
types/vector3/min.c \
types/vector3/max.c \
types/vector3/abs.c \
types/vector2/abs.c \
types/vector2/clamp.c \
types/vector2/comparisons.c \
types/vector2/cross.c \
types/vector2/dist.c \
types/vector2/dot.c \
types/vector2/len.c \
types/vector2/max.c \
types/vector2/min.c \
types/vector2/normalize.c \
types/vector2/operators.c \
types/vector2/operators_by.c \
types/vector2/other_operators.c \
types/vector2/other_operators_by.c \
types/mat2/get.c \
types/mat2/operators.c \
types/mat2/translate.c \
types/mat2/new.c \
types/mat2/dot.c \
types/mat2/xform.c \
types/mat2/rotate.c \
types/mat2/scale.c \
types/mat2/invert.c \
types/mat2/lerp.c \
engine.c
